# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Research
    url: '#research'
    weight: 20
  - name: Posts
    url: '#posts'
    weight: 30
  - name: Open-source
    url: '#projects'
    weight: 40
  #- name : Learn
  #  weight: 50
  #- parent: Learn
  #  name: (Book) Responsible AI - Theory and Practice
  #  url: https://responsibleaibook.netlify.app/intro.html
  #  weight: 10
  #- parent: Learn
  #  name: (Book in portuguese) Time Series - analysis and forecast in Python
  #  url: https://seriestemporais.netlify.app/intro.html
  #  weight: 20
  #- parent: Learn
  #  name: (Code) Machine Learning 101
  #  url: https://github.com/Kleyt0n/ml-101
  #  weight: 30
  #- name: Resume
  #  url: uploads/resume.pdf
  #  weight: 60